//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolClubs.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group_Student()
        {
            this.Raport_GroupStudent = new HashSet<Raport_GroupStudent>();
        }
    
        public int idGroup_Student { get; set; }
        public int idGroup { get; set; }
        public int idStudent { get; set; }
        public int idStudentStatus { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentStatus StudentStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raport_GroupStudent> Raport_GroupStudent { get; set; }
    }
}
