//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolClubs.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raport_GroupStudent
    {
        public int idRaport_GroupStudent { get; set; }
        public int idRaport { get; set; }
        public int idGroup_Student { get; set; }
        public int idRaportStatus { get; set; }
    
        public virtual Group_Student Group_Student { get; set; }
        public virtual Raport Raport { get; set; }
        public virtual RaportStatus RaportStatus { get; set; }
    }
}
