//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolClubs.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int idTimetable { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.TimeSpan Duration { get; set; }
        public int idRaport { get; set; }
        public Nullable<bool> isRaportCreated { get; set; }
    
        public virtual Raport Raport { get; set; }
    }
}
