//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolClubs.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Section = new HashSet<Section>();
        }

        public User(string name, string surname, string patronymic,  DateTime birthdate, decimal? experience, int idAuthorization)
        {
            Name = name;
            Surname = surname;
            Patronymic = patronymic;
            this.idRole = 2;
            Birthdate = birthdate;
            Experience = experience;
            this.idAuthorization = idAuthorization;
        }

        public int idUser { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int idRole { get; set; }
        public System.DateTime Birthdate { get; set; }
        public Nullable<decimal> Experience { get; set; }
        public int idAuthorization { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Section { get; set; }

        public int CountStudents { get; set; }

        public string sections { get; set; }

    }
}
