//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolClubs.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class School1Entities1 : DbContext
    {
        public School1Entities1()
            : base("name=School1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Group_Student> Group_Student { get; set; }
        public virtual DbSet<Raport> Raport { get; set; }
        public virtual DbSet<Raport_GroupStudent> Raport_GroupStudent { get; set; }
        public virtual DbSet<RaportStatus> RaportStatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentStatus> StudentStatus { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
