//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolClubs.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raport_GroupStudent
    {
        public int idRaport_GroupStudent { get; set; }
        public int idRaport { get; set; }
        public int idGroup_Student { get; set; }
    
        public virtual Group_Student Group_Student { get; set; }
        public virtual Raport Raport { get; set; }
    }
}
